language:
  - minimal

services:
  - docker

install:
  - docker pull jjmerelo/raku-test
  - docker images

script:  docker run -t  --entrypoint="/bin/sh" \
  -v  $TRAVIS_BUILD_DIR:/test jjmerelo/raku-test \
  -c "prove6 --lib
